from __future__ import annotations

import argparse
import re
from pathlib import Path

import numpy as np
import pandas as pd


# =======================================================
# Default configuration
# =======================================================
OER_OUTPUT_BASE_DIR = Path("output/OER")
CONDITIONS_CSV = Path(
    "input/conditions/electrodeposition_conditions_96cond_1.csv"
)
INPUT_RUN_DIRECTORY = Path(
    "output/OER/run_YYYYMMDD_HHMMSS"
)

WORKING_ELECTRODE_AREA_CM2 = 0.0264
POTENTIAL_CORRECTION_TO_RHE_V = 1.169
ZERO_POINT_DURATION_S = 1.0
ZERO_POTENTIAL_TOLERANCE_V = 1.0e-6

# Rodeostat CSV files generated by run_test() contain no header.
# The expected raw column order is:
#   time (s), applied potential (V), current (uA)
RAW_COLUMN_NAMES = ["time_s", "potential_V", "current_uA"]

# Tolerances used only to warn about differences in overlapping time
# and potential values. Files are still combined by row position.
TIME_ALIGNMENT_TOLERANCE_S = 1.0e-6
POTENTIAL_ALIGNMENT_TOLERANCE_V = 1.0e-6


def find_latest_run_directory(base_dir: Path) -> Path:
    """Return the latest run_* directory under the OER output directory."""
    if not base_dir.exists():
        raise FileNotFoundError(
            f"OER output base directory was not found: {base_dir}"
        )

    run_directories = sorted(
        path
        for path in base_dir.iterdir()
        if path.is_dir() and path.name.startswith("run_")
    )

    if not run_directories:
        raise FileNotFoundError(
            f"No run_* directories were found under: {base_dir}"
        )

    return run_directories[-1]


def read_condition_channels(conditions_csv: Path) -> pd.DataFrame:
    """
    Read the condition file and assign ch1, ch2, ... in row order.

    The COM port in each row is used to associate the condition row with
    the corresponding Rodeostat output filename.
    """
    if not conditions_csv.exists():
        raise FileNotFoundError(
            f"Condition CSV was not found: {conditions_csv}"
        )

    conditions = pd.read_csv(conditions_csv, encoding="utf-8-sig")

    required_columns = {"port"}
    missing_columns = required_columns - set(conditions.columns)
    if missing_columns:
        raise ValueError(
            f"Condition CSV is missing required columns: "
            f"{sorted(missing_columns)}"
        )

    conditions = conditions.copy()
    conditions["port"] = conditions["port"].astype(str).str.strip()

    if conditions["port"].eq("").any():
        empty_rows = conditions.index[conditions["port"].eq("")].tolist()
        raise ValueError(
            f"Empty COM-port values were found at zero-based rows: {empty_rows}"
        )

    duplicated_ports = conditions.loc[
        conditions["port"].duplicated(keep=False), "port"
    ].tolist()
    if duplicated_ports:
        raise ValueError(
            f"Duplicate COM ports were found in the condition CSV: "
            f"{sorted(set(duplicated_ports))}"
        )

    conditions.insert(
        0,
        "channel",
        [f"ch{index}" for index in range(1, len(conditions) + 1)],
    )

    return conditions


def read_headerless_rodeostat_csv(csv_path: Path) -> pd.DataFrame:
    """
    Read one headerless Rodeostat output CSV.

    The first three columns are interpreted as time (s), potential (V),
    and current (uA). Empty and nonnumeric rows are removed.
    """
    dataframe = pd.read_csv(
        csv_path,
        header=None,
        comment="#",
        skip_blank_lines=True,
    )

    if dataframe.shape[1] < 3:
        raise ValueError(
            f"{csv_path.name} contains {dataframe.shape[1]} columns; "
            "at least three columns are required."
        )

    dataframe = dataframe.iloc[:, :3].copy()
    dataframe.columns = RAW_COLUMN_NAMES

    for column in RAW_COLUMN_NAMES:
        dataframe[column] = pd.to_numeric(
            dataframe[column],
            errors="coerce",
        )

    dataframe = dataframe.dropna(
        subset=RAW_COLUMN_NAMES
    ).reset_index(drop=True)

    if dataframe.empty:
        raise ValueError(
            f"No numeric time-potential-current rows were found in: {csv_path}"
        )

    return dataframe


def current_uA_to_current_density_mA_cm2(
    current_uA: pd.Series,
    electrode_area_cm2: float,
) -> pd.Series:
    """Convert current in uA to current density in mA cm^-2."""
    if electrode_area_cm2 <= 0:
        raise ValueError(
            "Working-electrode area must be greater than zero."
        )

    return current_uA / 1000.0 / electrode_area_cm2


def calculate_zero_point_corrected_current_density(
    data: pd.DataFrame,
    electrode_area_cm2: float,
) -> tuple[pd.Series, float, int]:
    """
    Convert current to mA/cm^2 and apply channel-specific zero-point correction.

    The zero-current baseline is the mean current density measured during the
    initial waiting period in which the unconverted potential is 0 V and
    time_s is between 0 and ZERO_POINT_DURATION_S, inclusive. The baseline
    is subtracted from every current-density value in the channel.
    """
    current_density = current_uA_to_current_density_mA_cm2(
        data["current_uA"],
        electrode_area_cm2,
    ).reset_index(drop=True)

    zero_mask = (
        data["time_s"].between(
            0.0,
            ZERO_POINT_DURATION_S,
            inclusive="both",
        )
        & data["potential_V"].abs().le(ZERO_POTENTIAL_TOLERANCE_V)
    )

    zero_point_count = int(zero_mask.sum())
    if zero_point_count == 0:
        raise ValueError(
            "No data points were found for zero-point correction. "
            f"Expected raw potential = 0 V within the first "
            f"{ZERO_POINT_DURATION_S} s."
        )

    zero_point_mean_mA_cm2 = float(
        current_density.loc[zero_mask.to_numpy()].mean()
    )
    corrected_current_density = (
        current_density - zero_point_mean_mA_cm2
    )

    return (
        corrected_current_density,
        zero_point_mean_mA_cm2,
        zero_point_count,
    )


def filename_contains_port(filename: str, port: str) -> bool:
    """
    Return True when a filename contains the complete COM-port token.

    Token boundaries prevent COM1 from being incorrectly matched to COM10.
    """
    pattern = rf"(^|_){re.escape(port)}(_|$)"
    return re.search(pattern, filename, flags=re.IGNORECASE) is not None


def map_output_files_to_channels(
    input_directory: Path,
    conditions: pd.DataFrame,
    output_csv: Path,
) -> dict[str, Path]:
    """Associate each Rodeostat output CSV with ch1, ch2, ... using COM ports."""
    all_csv_files = sorted(
        path
        for path in input_directory.glob("*.csv")
        if path.resolve() != output_csv.resolve()
    )

    if not all_csv_files:
        raise FileNotFoundError(
            f"No CSV files were found in: {input_directory}"
        )

    channel_to_file: dict[str, Path] = {}
    used_files: set[Path] = set()

    for row in conditions.itertuples(index=False):
        channel = str(row.channel)
        port = str(row.port)

        matching_files = [
            path
            for path in all_csv_files
            if filename_contains_port(path.stem, port)
        ]

        if len(matching_files) > 1:
            raise ValueError(
                f"Multiple output files matched {channel} ({port}): "
                f"{[path.name for path in matching_files]}"
            )

        if len(matching_files) == 1:
            matched_file = matching_files[0]
            channel_to_file[channel] = matched_file
            used_files.add(matched_file)

    unmatched_files = [
        path.name for path in all_csv_files if path not in used_files
    ]
    if unmatched_files:
        print(
            "[WARNING] CSV files not matched to a condition-file COM port: "
            + ", ".join(unmatched_files)
        )

    return channel_to_file


def warn_if_overlapping_axes_differ(
    reference_data: pd.DataFrame,
    channel_data: pd.DataFrame,
    channel: str,
    source_path: Path,
) -> None:
    """
    Warn when overlapping rows have different time or potential values.

    Different total lengths are allowed. The combined output is aligned by
    row position, and missing trailing values are written as blank cells.
    """
    overlap_length = min(len(reference_data), len(channel_data))
    if overlap_length == 0:
        return

    reference_overlap = reference_data.iloc[:overlap_length]
    channel_overlap = channel_data.iloc[:overlap_length]

    time_matches = np.allclose(
        reference_overlap["time_s"].to_numpy(),
        channel_overlap["time_s"].to_numpy(),
        rtol=0.0,
        atol=TIME_ALIGNMENT_TOLERANCE_S,
        equal_nan=False,
    )
    potential_matches = np.allclose(
        reference_overlap["potential_V"].to_numpy(),
        channel_overlap["potential_V"].to_numpy(),
        rtol=0.0,
        atol=POTENTIAL_ALIGNMENT_TOLERANCE_V,
        equal_nan=False,
    )

    if not time_matches:
        print(
            f"[WARNING] The overlapping time axis for {channel} "
            f"({source_path.name}) differs from the reference channel. "
            "Values are still aligned by row position."
        )

    if not potential_matches:
        print(
            f"[WARNING] The overlapping potential axis for {channel} "
            f"({source_path.name}) differs from the reference channel. "
            "Values are still aligned by row position."
        )


def combine_oer_current_density(
    input_directory: Path,
    conditions_csv: Path,
    output_csv: Path,
    electrode_area_cm2: float,
) -> Path:
    """
    Combine channel-specific Rodeostat OER outputs into one CSV.

    Output columns:
        time_s
        potential_V_vs_RHE
        ch1, ch2, ..., chN

    The ch columns contain zero-point-corrected current density in mA/cm^2.
    Channel numbering follows the row order of the supplied condition CSV.

    When channel files have different lengths, the longest file determines the
    output row count. Shorter channels are padded with blank cells (NaN) after
    their final measured value.
    """
    if not input_directory.exists():
        raise FileNotFoundError(
            f"Input run directory was not found: {input_directory}"
        )
    if not input_directory.is_dir():
        raise NotADirectoryError(
            f"The input path is not a directory: {input_directory}"
        )
    if electrode_area_cm2 <= 0:
        raise ValueError(
            "Working-electrode area must be greater than zero."
        )

    conditions = read_condition_channels(conditions_csv)
    channel_to_file = map_output_files_to_channels(
        input_directory=input_directory,
        conditions=conditions,
        output_csv=output_csv,
    )

    if not channel_to_file:
        raise FileNotFoundError(
            "None of the Rodeostat output files could be matched to the "
            "COM ports in the condition CSV."
        )

    channel_data: dict[str, pd.DataFrame] = {}
    for channel, csv_path in channel_to_file.items():
        channel_data[channel] = read_headerless_rodeostat_csv(csv_path)

    # Use the longest valid file as the common displayed time/potential axis.
    reference_channel = max(
        channel_data,
        key=lambda channel: len(channel_data[channel]),
    )
    reference_data = channel_data[reference_channel]
    maximum_length = len(reference_data)

    combined = pd.DataFrame(
        {
            "time_s": reference_data["time_s"].reset_index(drop=True),
            "potential_V_vs_RHE": (
                reference_data["potential_V"].reset_index(drop=True)
                + POTENTIAL_CORRECTION_TO_RHE_V
            ),
        }
    )

    # Add channels in condition-file order, including entirely missing channels.
    for row in conditions.itertuples(index=False):
        channel = str(row.channel)

        if channel not in channel_data:
            combined[channel] = np.nan
            print(
                f"[WARNING] No output file was found for "
                f"{channel} ({row.port}); the column is blank."
            )
            continue

        data = channel_data[channel]
        warn_if_overlapping_axes_differ(
            reference_data=reference_data,
            channel_data=data,
            channel=channel,
            source_path=channel_to_file[channel],
        )

        (
            corrected_current_density,
            zero_point_mean_mA_cm2,
            zero_point_count,
        ) = calculate_zero_point_corrected_current_density(
            data=data,
            electrode_area_cm2=electrode_area_cm2,
        )

        print(
            f"[ZERO CORRECTION] {channel}: "
            f"mean={zero_point_mean_mA_cm2:.9g} mA/cm^2 "
            f"from {zero_point_count} points"
        )

        combined[channel] = corrected_current_density.reindex(
            range(maximum_length)
        )

    output_csv.parent.mkdir(parents=True, exist_ok=True)
    combined.to_csv(
        output_csv,
        index=False,
        encoding="utf-8-sig",
    )

    print(f"Input directory: {input_directory}")
    print(f"Condition CSV: {conditions_csv}")
    print(f"Condition channels: {len(conditions)}")
    print(f"Matched measurement files: {len(channel_to_file)}")
    print(
        f"Reference axis: {reference_channel} "
        f"({channel_to_file[reference_channel].name})"
    )
    print(f"Output rows: {maximum_length}")
    print(f"Working-electrode area: {electrode_area_cm2} cm^2")
    print(
        f"Potential correction to RHE: "
        f"+{POTENTIAL_CORRECTION_TO_RHE_V} V"
    )
    print("Potential unit: V vs RHE")
    print(
        f"Zero-point interval: raw potential = 0 V during "
        f"0-{ZERO_POINT_DURATION_S} s"
    )
    print("Units of ch1, ch2, ...: mA/cm^2")
    print(f"Output columns: {list(combined.columns)}")
    print(f"Output CSV: {output_csv}")

    return output_csv


def parse_arguments() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        description=(
            "Combine headerless Rodeostat OER output files into a channel "
            "matrix with current density in mA/cm^2."
        )
    )
    parser.add_argument(
        "--input-dir",
        type=Path,
        default=None,
        help=(
            "OER run directory containing raw CSV files. When omitted, "
            "the latest output/OER/run_* directory is selected."
        ),
    )
    parser.add_argument(
        "--conditions",
        type=Path,
        default=CONDITIONS_CSV,
        help=(
            "Condition CSV used for the OER measurement. Its row order "
            "defines ch1, ch2, ... ."
        ),
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help=(
            "Output CSV path. When omitted, combined_current_density.csv "
            "is created inside the selected run directory."
        ),
    )
    parser.add_argument(
        "--area-cm2",
        type=float,
        default=WORKING_ELECTRODE_AREA_CM2,
        help=(
            "Geometric working-electrode area in cm^2 "
            f"(default: {WORKING_ELECTRODE_AREA_CM2})."
        ),
    )
    return parser.parse_args()


def main() -> None:
    """Select the input files and generate the combined channel matrix."""
    arguments = parse_arguments()

    input_directory = (
        arguments.input_dir
        if arguments.input_dir is not None
        else find_latest_run_directory(OER_OUTPUT_BASE_DIR)
    )

    output_csv = (
        arguments.output
        if arguments.output is not None
        else input_directory / "combined_current_density.csv"
    )

    combine_oer_current_density(
        input_directory=input_directory,
        conditions_csv=arguments.conditions,
        output_csv=output_csv,
        electrode_area_cm2=arguments.area_cm2,
    )


if __name__ == "__main__":
    input_directory = INPUT_RUN_DIRECTORY
    main()
